name: Docker Build and Push to GHCR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REPO_NAME: "{{ github.event.repository.name }}"
  LOWERCASE_REPO_NAME: "${{ env.REPO_NAME }}".toLowerCase()

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.LOWERCASE_REPO_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.LOWERCASE_REPO_NAME }}:${{ github.sha }}
